### ISSUE TITLE
Changes and Improvements

### ISSUE THREAD

**Issue by suhasks123** [DeltaCube23/chat_app#1]
1. https://github.com/DeltaCube23/chat_app/blob/d0556c980435f50b31316cfa8ee532cd8800a7ce/server/server.go#L163

    So I'll briefly explain how the context package plays into this application. The main application is the `chat_app` process and this will have a 'context' object. If we start a server, we'll have a context object that is derived from the original chat_app process.

    Any context can be canceled using the corresponding cancel function of the type 'CancelType'. When you cancel some context, all the contexts derived from it are canceled. `Canceling` a context means that you're adding a message to the `Done` channel of that context. Every time you create a context, you get a channel `Done` along with it. This can be accessed as `context.Done()`.You can use this to see if the corresponding context is canceled. This information can be used to exit go routines 
 pawned from a process.

    For example, the server spawns a number of go routines for several procedures. The functions in each of these threads are given the main server context. If the server exits for whatever reason, all these threads need to exit as well. They will get to know that the server exited only using the `context.Done()`. Or maybe a thread is very integral to the working of the server, so much that the exiting of the thread should terminate the server. This can also be enforced using the cancel function of the server context. If code for handling such cancelations is written, then the server will terminate when the thread stops. In this way, the context package is very useful for such goroutine heavy applications.

    One example that I can give from your code is your thread to handle interrupts which is managed by the function `gracexit()`. The process should exit in that situation, but then how to convey this to the main thread on which the server is running? You create a main context which this `gracexit()` function holds and derive a context from it for the server context. That way, when there is an interrupt, you can cancel the main context, which will cancel the derived server context, and with appropriate context cancelation handling mechanism in your server code, the thread running the server will exit as well. With proper context cancelation handling mechanisms in all the goroutines spawned by the server thread, all of them will exit.

    Try to use the context package with this in mind.

2. https://github.com/DeltaCube23/chat_app/blob/d0556c980435f50b31316cfa8ee532cd8800a7ce/server/server.go#L164

    It's a good idea to give the user the option to set the port number for the server. Extending this, the client program should ask the user to enter the IP address and port number for the target chat server. As this application stands right now, it can only be run when the server process and the client process are on the same machine.

3. https://github.com/DeltaCube23/chat_app/blob/d0556c980435f50b31316cfa8ee532cd8800a7ce/server/server.go#L169

    Write a message here to let the user know that the server is online

4. https://github.com/DeltaCube23/chat_app/blob/d0556c980435f50b31316cfa8ee532cd8800a7ce/client/client.go#L63

    This kind of an input handling mechanism requires the user to add a '$' at the end of every command. It makes the
usage unnecessarily complicated for the end user. I know that the delimiter is a part of your protocol but try to do the processing of adding the '$' character in the application itself. This isn't really a functional change but more of a QOL improvement. I believe it can be added by simply appending a '$' to the `msg` variable.

5. https://github.com/DeltaCube23/chat_app/blob/d0556c980435f50b31316cfa8ee532cd8800a7ce/client/client.go#L71

    The prompt '>>' isn't printed consistently. When a new message is read, the prompt goes away, so the user is not sure if the program is doing some processing or it is actually ready for a message. You can add the prompt in the `for` loop right after the `select` block.

6. https://github.com/DeltaCube23/chat_app/blob/d0556c980435f50b31316cfa8ee532cd8800a7ce/client/client.go#L84

    Ideally, the client should ask for the target chat server's IP address and port number from the user for establishing connection. While it works right now, this kind of hardcoding will not work in a practical situation where the server and the client are on different machines. Keep the current values as 'default', in case the user doesn't enter an IP address or port name.

**Comment by DeltaCube23** [comment]
I believe all suggested changes have been done.
